---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server
  labels:
    app: cloud-config-server
    version: 0.0.2
spec:
  selector:
    matchLabels:
      app: cloud-config-server
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-config-server
    spec:
      containers:
      - name: cloud-config-server
        image: mirrors.cloud.com:5000/app/cloud-config-server:0.0.2
        imagePullPolicy: Always
        env:
        - name: eureka_host
          value: "eureka.default.svc.cluster.local"
        - name: eureka_port
          value: "8761"
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server
  labels:
    app: cloud-config-server
    version: 0.0.2
spec:
  selector:
    app: cloud-config-server
  type: LoadBalancer      
  ports:
  - name: tcp-8761-8761
    protocol: TCP
    port: 8761
    targetPort: 8761